# Fixtures/SimplePodfile/Podfile
platform :ios, '14.0'
use_frameworks!

target 'MyApp' do
  pod 'Alamofire', '~> 5.6'
  pod 'SwiftyJSON', '~> 5.0'
end

target 'MyAppTests' do
  inherit! :search_paths
  pod 'Quick'
end
