import Darwin
import Dispatch
import Foundation
import PkgLiftCore
import XCTest
@testable import PkgLiftCLI

/// Exact project.xcproj files generated by upstream XcodeProj 9.17.5 from
/// Fixtures/PartialSwift. These frozen bytes also compile with XcodeProj 9.16.0.
/// The explicit variant previously yielded a real KeychainAccess AUTO plan and
/// created a second project definition during apply. The implicit variant
/// lacks source-type evidence; both formats must be refused before analysis.
final class UnsupportedProjectFormatTests: XCTestCase {
    private static let childApplyRoot = "PKGLIFT_UNSUPPORTED_FORMAT_APPLY_ROOT"
    private static let projectName = "SwiftKeychainAccess.xcodeproj"

    func testJSONOnlyExplicitSwiftTypesRefusedAtEveryCLIEntry() async throws {
        try await assertCommandsRefuse(.explicit)
    }

    func testJSONOnlyImplicitSwiftTypesRefusedAtEveryCLIEntry() async throws {
        try await assertCommandsRefuse(.implicit)
    }

    func testDualProjectDefinitionsRefusedAtEveryCLIEntry() async throws {
        try await assertCommandsRefuse(.dual)
    }

    /// Apply uses signal handlers if it unexpectedly reaches migration. A
    /// separate XCTest process keeps that path isolated from the test runner.
    func testChildProcessRefusesUnsupportedApply() async throws {
        guard let root = ProcessInfo.processInfo.environment[Self.childApplyRoot] else {
            return
        }
        let project = URL(fileURLWithPath: root, isDirectory: true)
            .appendingPathComponent(Self.projectName, isDirectory: true)
        var command = try MigrateCommand.parse([
            "--path", root, "--project", project.path, "--apply",
        ])
        await assertUnsupported { try await command.run() }
    }

    private func assertCommandsRefuse(_ mode: Mode) async throws {
        var fixture = try Fixture(mode: mode)
        defer { try? FileManager.default.removeItem(at: fixture.root) }
        try await fixture.prepare()
        let arguments = ["--path", fixture.root.path, "--project", fixture.project.path]
        let savedBytes = try fixture.originalBytes()
        XCTAssertEqual(try gitOutput(["status", "--porcelain"], in: fixture.root), "")

        var analyze = try AnalyzeCommand.parse(arguments)
        await assertUnsupported { try await analyze.run() }
        try fixture.assertUnchanged(savedBytes)

        var plan = try PlanCommand.parse(arguments)
        await assertUnsupported { try await plan.run() }
        try fixture.assertUnchanged(savedBytes)

        var dryRun = try MigrateCommand.parse(arguments)
        await assertUnsupported { try await dryRun.run() }
        try fixture.assertUnchanged(savedBytes)

        var verify = try VerifyCommand.parse(arguments)
        await assertUnsupported { try await verify.run() }
        try fixture.assertUnchanged(savedBytes)

        try runApplyInFreshXCTestProcess(root: fixture.root)
        try fixture.assertUnchanged(savedBytes)
        XCTAssertEqual(try gitOutput(["status", "--porcelain"], in: fixture.root), "")
    }

    private func assertUnsupported(_ operation: () async throws -> Void) async {
        do {
            try await operation()
            XCTFail("Unsupported project.xcproj was accepted")
        } catch {
            let diagnostic = error.localizedDescription.lowercased()
            XCTAssertTrue(diagnostic.contains("unsupported"), diagnostic)
            XCTAssertTrue(diagnostic.contains("project.xcproj"), diagnostic)
        }
    }

    private func runApplyInFreshXCTestProcess(root: URL) throws {
        let lookup = Process()
        lookup.executableURL = URL(fileURLWithPath: "/usr/bin/xcrun")
        lookup.arguments = ["--find", "xctest"]
        let lookupOutput = Pipe()
        lookup.standardOutput = lookupOutput
        lookup.standardError = FileHandle.nullDevice
        try lookup.run()
        lookup.waitUntilExit()
        guard lookup.terminationStatus == 0 else { throw TestError.xctestUnavailable }
        let executable = String(
            decoding: lookupOutput.fileHandleForReading.readDataToEndOfFile(),
            as: UTF8.self
        ).trimmingCharacters(in: .whitespacesAndNewlines)
        guard !executable.isEmpty else { throw TestError.xctestUnavailable }

        let process = Process()
        process.executableURL = URL(fileURLWithPath: executable)
        process.arguments = [
            "-XCTest",
            "PkgLiftCLITests.UnsupportedProjectFormatTests/testChildProcessRefusesUnsupportedApply",
            Bundle(for: Self.self).bundleURL.path,
        ]
        var environment = ProcessInfo.processInfo.environment
        environment[Self.childApplyRoot] = root.path
        process.environment = environment
        process.standardOutput = FileHandle.nullDevice
        let standardError = Pipe()
        process.standardError = standardError
        let finished = DispatchSemaphore(value: 0)
        process.terminationHandler = { _ in finished.signal() }
        try process.run()
        guard finished.wait(timeout: .now() + 30) == .success else {
            _ = Darwin.kill(process.processIdentifier, SIGKILL)
            process.waitUntilExit()
            throw TestError.childTimedOut
        }
        let diagnostic = String(
            decoding: standardError.fileHandleForReading.readDataToEndOfFile(),
            as: UTF8.self
        )
        XCTAssertEqual(process.terminationReason, .exit, diagnostic)
        XCTAssertEqual(process.terminationStatus, 0, diagnostic)
    }

    private enum Mode: CaseIterable {
        case explicit
        case implicit
        case dual

        var json: String {
            switch self {
            case .explicit, .dual: Self.explicitXCProj
            case .implicit: Self.implicitXCProj
            }
        }

        var name: String {
            switch self {
            case .explicit: "explicit"
            case .implicit: "implicit"
            case .dual: "dual"
            }
        }

        // SHA-256 cf9ec7127d7b3bf7f18cbea51d4f995b5ea906ab4c1f122a5edafe145126f995.
        private static let explicitXCProj = #"""
{
  "default-configuration": "Release",
  "configurations": [
    "Debug",
    "Release",
  ],
  "localizations": {
    "development": "en",
    "supported": [
      "Base",
    ],
  },
  "files": [
    {
      "kind": "group",
      "path": "App",
      "children": [
        { "path": "AppDelegate.swift", "type": "sourcecode.swift", "target-membership": [ "SwiftKeychainAccess/compile-sources" ] },
        { "path": "Consumer.swift", "type": "sourcecode.swift", "target-membership": [ "SwiftKeychainAccess/compile-sources" ] },
        { "path": "Fixture.txt", "target-membership": [ "SwiftKeychainAccess/resources" ] },
      ],
    }, {
      "kind": "group",
      "name": "Products",
      "children": [
        { "path": "<PRODUCTS>/SwiftKeychainAccess.app", "id": "B10000000000000000000004", "type": "wrapper.application", "index": false },
      ],
    },
  ],
  "targets": [
    {
      "name": "SwiftKeychainAccess",
      "id": "E10000000000000000000001",
      "product": "Products/SwiftKeychainAccess.app",
      "product-type": "application",
      "build-phases": [
        "compile-sources",
        "frameworks",
        "resources",
      ],
      "build-settings": {
        "CODE_SIGN_STYLE": "Automatic",
        "CURRENT_PROJECT_VERSION": "1",
        "GENERATE_INFOPLIST_FILE": "YES",
        "INFOPLIST_KEY_UILaunchScreen_Generation": "YES",
        "LD_RUNPATH_SEARCH_PATHS": "$(inherited) @executable_path/Frameworks",
        "MARKETING_VERSION": "1.0",
        "PRODUCT_BUNDLE_IDENTIFIER": "dev.pkglift.SwiftKeychainAccess",
        "PRODUCT_NAME": "$(TARGET_NAME)",
        "SWIFT_VERSION": "5.0",
        "TARGETED_DEVICE_FAMILY": "1,2",
      },
    },
  ],
  "build-settings": {
    "ALWAYS_SEARCH_USER_PATHS": "NO",
    "CLANG_ENABLE_MODULES": "YES",
    "CLANG_ENABLE_OBJC_ARC": "YES",
    "GCC_C_LANGUAGE_STANDARD": "gnu17",
    "IPHONEOS_DEPLOYMENT_TARGET": "15.0",
    "SDKROOT": "iphoneos",
    "SWIFT_ACTIVE_COMPILATION_CONDITIONS[config=Debug]": "DEBUG $(inherited)",
    "SWIFT_COMPILATION_MODE[config=Release]": "wholemodule",
  },
  "last-upgrade": "16.0",
  "last-swift-update": "16.0",
}
"""# + "\n"

        // SHA-256 b75ca9dacf87246d5c5267ccb33f7709131a3176103923280a7954a322c31148.
        private static let implicitXCProj = #"""
{
  "default-configuration": "Release",
  "configurations": [
    "Debug",
    "Release",
  ],
  "localizations": {
    "development": "en",
    "supported": [
      "Base",
    ],
  },
  "files": [
    {
      "kind": "group",
      "path": "App",
      "children": [
        { "path": "AppDelegate.swift", "target-membership": [ "SwiftKeychainAccess/compile-sources" ] },
        { "path": "Consumer.swift", "target-membership": [ "SwiftKeychainAccess/compile-sources" ] },
        { "path": "Fixture.txt", "target-membership": [ "SwiftKeychainAccess/resources" ] },
      ],
    }, {
      "kind": "group",
      "name": "Products",
      "children": [
        { "path": "<PRODUCTS>/SwiftKeychainAccess.app", "id": "B10000000000000000000004", "type": "wrapper.application", "index": false },
      ],
    },
  ],
  "targets": [
    {
      "name": "SwiftKeychainAccess",
      "id": "E10000000000000000000001",
      "product": "Products/SwiftKeychainAccess.app",
      "product-type": "application",
      "build-phases": [
        "compile-sources",
        "frameworks",
        "resources",
      ],
      "build-settings": {
        "CODE_SIGN_STYLE": "Automatic",
        "CURRENT_PROJECT_VERSION": "1",
        "GENERATE_INFOPLIST_FILE": "YES",
        "INFOPLIST_KEY_UILaunchScreen_Generation": "YES",
        "LD_RUNPATH_SEARCH_PATHS": "$(inherited) @executable_path/Frameworks",
        "MARKETING_VERSION": "1.0",
        "PRODUCT_BUNDLE_IDENTIFIER": "dev.pkglift.SwiftKeychainAccess",
        "PRODUCT_NAME": "$(TARGET_NAME)",
        "SWIFT_VERSION": "5.0",
        "TARGETED_DEVICE_FAMILY": "1,2",
      },
    },
  ],
  "build-settings": {
    "ALWAYS_SEARCH_USER_PATHS": "NO",
    "CLANG_ENABLE_MODULES": "YES",
    "CLANG_ENABLE_OBJC_ARC": "YES",
    "GCC_C_LANGUAGE_STANDARD": "gnu17",
    "IPHONEOS_DEPLOYMENT_TARGET": "15.0",
    "SDKROOT": "iphoneos",
    "SWIFT_ACTIVE_COMPILATION_CONDITIONS[config=Debug]": "DEBUG $(inherited)",
    "SWIFT_COMPILATION_MODE[config=Release]": "wholemodule",
  },
  "last-upgrade": "16.0",
  "last-swift-update": "16.0",
}
"""# + "\n"
    }

    private struct Fixture {
        let root: URL
        let project: URL
        let xcproj: URL
        let pbxproj: URL
        let plan: URL
        let mode: Mode

        init(mode: Mode) throws {
            self.mode = mode
            let checkout = URL(fileURLWithPath: #filePath)
                .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
            let source = checkout.appendingPathComponent("Fixtures/PartialSwift", isDirectory: true)
            let temporaryRoot: URL
            if let selected = ProcessInfo.processInfo.environment["PKGLIFT_TEST_TEMP_ROOT"] {
                var isDirectory: ObjCBool = false
                guard !selected.isEmpty,
                      FileManager.default.fileExists(atPath: selected, isDirectory: &isDirectory),
                      isDirectory.boolValue else {
                    throw TestError.invalidTemporaryRoot(selected)
                }
                temporaryRoot = URL(fileURLWithPath: selected, isDirectory: true)
            } else {
                temporaryRoot = FileManager.default.temporaryDirectory
            }
            root = temporaryRoot
                .appendingPathComponent("PkgLiftUnsupportedFormat-\(mode.name)-\(UUID().uuidString)", isDirectory: true)
            try FileManager.default.copyItem(at: source, to: root)
            project = root.appendingPathComponent(UnsupportedProjectFormatTests.projectName, isDirectory: true)
            pbxproj = project.appendingPathComponent("project.pbxproj")
            xcproj = project.appendingPathComponent("project.xcproj")
            plan = root.appendingPathComponent(".pkglift/plan.json")
        }

        func prepare() async throws {
            // Generate a real, registry-backed saved plan on the supported
            // project. Its KeychainAccess AUTO route is the apply precondition.
            let arguments = ["--path", root.path, "--project", project.path]
            var planCommand = try PlanCommand.parse(arguments)
            try await planCommand.run()
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .iso8601
            let savedPlan = try decoder.decode(MigrationPlan.self, from: Data(contentsOf: plan))
            XCTAssertEqual(savedPlan.autoEntries.map(\.podName), ["KeychainAccess"])
            guard savedPlan.autoEntries.map(\.podName) == ["KeychainAccess"] else {
                throw TestError.supportedPlanMissingAuto
            }
            var dryRun = try MigrateCommand.parse(arguments)
            try await dryRun.run()

            if mode != .dual {
                try FileManager.default.removeItem(at: pbxproj)
            }
            try Data(mode.json.utf8).write(to: xcproj)
            try ".pkglift/plan.json\n".write(
                to: root.appendingPathComponent(".gitignore"),
                atomically: true,
                encoding: .utf8
            )
            try runGit(["init", "--quiet"], in: root)
            try runGit(["config", "user.email", "format-test@example.invalid"], in: root)
            try runGit(["config", "user.name", "PkgLift Format Test"], in: root)
            try runGit(["config", "commit.gpgsign", "false"], in: root)
            try runGit(["add", "."], in: root)
            try runGit(["commit", "--quiet", "-m", "supported-plan baseline"], in: root)
        }

        func originalBytes() throws -> [URL: Data] {
            var files = [
                root.appendingPathComponent("Podfile"),
                root.appendingPathComponent("Podfile.lock"),
                root.appendingPathComponent(".pkglift.yml"),
                root.appendingPathComponent(".gitignore"),
                root.appendingPathComponent("App/AppDelegate.swift"),
                root.appendingPathComponent("App/Consumer.swift"),
                root.appendingPathComponent("App/Fixture.txt"),
                project.appendingPathComponent("xcshareddata/xcschemes/SwiftKeychainAccess.xcscheme"),
                xcproj,
                plan,
            ]
            if mode == .dual { files.append(pbxproj) }
            var bytes: [URL: Data] = [:]
            for file in files { bytes[file] = try Data(contentsOf: file) }
            return bytes
        }

        func assertUnchanged(_ savedBytes: [URL: Data]) throws {
            for (file, original) in savedBytes {
                XCTAssertEqual(try Data(contentsOf: file), original, file.path)
            }
            XCTAssertFalse(
                FileManager.default.fileExists(atPath: root.appendingPathComponent(".pkglift/backup").path),
                "Unsupported format must be refused before backup creation"
            )
            let children = try Set(FileManager.default.contentsOfDirectory(atPath: project.path))
            let expected: Set<String> = mode == .dual
                ? ["project.xcproj", "project.pbxproj", "xcshareddata"]
                : ["project.xcproj", "xcshareddata"]
            XCTAssertEqual(children, expected)
        }
    }

    private enum TestError: LocalizedError {
        case xctestUnavailable
        case childTimedOut
        case supportedPlanMissingAuto
        case invalidTemporaryRoot(String)

        var errorDescription: String? {
            switch self {
            case .xctestUnavailable: "Could not find xctest"
            case .childTimedOut: "Apply child process timed out"
            case .supportedPlanMissingAuto: "Supported fixture did not produce KeychainAccess AUTO"
            case .invalidTemporaryRoot(let path): "Test temporary root is unavailable: \(path)"
            }
        }
    }
}

private func runGit(_ arguments: [String], in root: URL) throws {
    _ = try gitOutput(arguments, in: root)
}

private func gitOutput(_ arguments: [String], in root: URL) throws -> String {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = arguments
    process.currentDirectoryURL = root
    let output = Pipe()
    process.standardOutput = output
    process.standardError = output
    try process.run()
    process.waitUntilExit()
    let value = String(decoding: output.fileHandleForReading.readDataToEndOfFile(), as: UTF8.self)
    guard process.terminationStatus == 0 else {
        throw GitTestError.failed(arguments.joined(separator: " "), value)
    }
    return value.trimmingCharacters(in: .whitespacesAndNewlines)
}

private enum GitTestError: LocalizedError {
    case failed(String, String)

    var errorDescription: String? {
        switch self {
        case .failed(let arguments, let output): "git \(arguments) failed: \(output)"
        }
    }
}
