name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer
    steps:
      - uses: actions/checkout@v6
      - name: Swift Version
        run: swift --version
      - name: Build
        run: swift build
